---
- name: "Gather facts"
  hosts: PlanetExpress
  gather_facts: True
  tasks:
  - ping:

- name: "Build hosts file"
  hosts: localhost
  gather_facts: False
  tasks:
  - lineinfile:
      state: present
      create: yes
      dest: "{{ lookup('env', 'PWD') }}/generated/hosts"
      mode: 0644
      regexp: '.*{{ item }}$'
      #line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
      line: "{{ hostvars[item].ansible_facts.all_ipv4_addresses | join(' ') }} {{item}}"
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: "{{ groups['PlanetExpress'] }}"
