---
- import_playbook: distribute_key.yml
  tags:
    - never
    - keys

- import_playbook: setup_wifi.yml
  tags:
    - never
    - wifi

- name: Set default OS user
  hosts: all
  gather_facts: yes
  tags:
    - always
  tasks:
    - name: Set default OS user (Ubuntu)
      set_fact:
        default_os_user: ubuntu
      when: ansible_lsb.id == "Ubuntu"
    - name: Set default OS user (Raspbian)
      set_fact:
        default_os_user: pi
      when: ansible_lsb.id == "Raspbian"

- name: Add a custom Pi system user
  hosts: new
  become: yes
  remote_user: "{{ default_os_user }}"
  vars:
    ansible_become_password: "{{ lookup('env', 'DEFAULT_PASS') }}"
  roles:
    - pi_user

- name: Perform common device setup
  hosts: Pis
  become: yes
  remote_user: "{{ pi_user }}"
  vars:
    ansible_become_password: "{{ lookup('env', 'BECOME_PASS') }}"
  roles:
    - common
  tags:
    - common

- name: Create Ansible control nodes
  hosts: ansible
  become: yes
  remote_user: "{{ pi_user }}"
  vars:
    ansible_become_password: "{{ lookup('env', 'BECOME_PASS') }}"
  roles:
    - ansible
  tags:
    - ansible
