---
- name: Ensure groups exist
  group:
    name: "{{ item }}"
    state: present
  loop:
  - ssh
  - sudo

- name: Add our main user
  user:
    name: "{{ pi_user }}"
    state: present
    append: yes
    groups:
      - ssh
      - sudo
    shell: /bin/bash
    password: "{{ pi_user_pass }}"
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_files: .ssh/id_ed25519
    ssh_key_passphrase: "{{ lookup('env','KEY_PASS') }}"

- name: Copy Ansible user's ssh key to the main user's authorized keys
  authorized_key:
    key: "{{ lookup('file',lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
    user: "{{ pi_user }}"
    state: present
