---
- name: Ensure the latest version of pip is installed
  pip:
    state: latest
    name: pip

- name: Install Ansible via pip
  pip:
    state: present
    name: ansible

- name: Install sshpass for distribute_key
  apt:
    state: present
    name: sshpass
